### ISSUE TITLE
Font end for news project

### ISSUE THREAD

**Issue by sunayana17** [sunayana17/NewsProject#1]
1. Create a frontend web application for the news application using the open source news API.
2. For now display the URL of the actual news article with the headline and a picture.
3. Create a search bar where user can enter a keyword or country to search news.

**Comment by dem0nsl4yer** [comment]
Hi @sunayana17 this project for summarizing news sounds interesting and I would like to work on the issue you created.

**Comment by sunayana17** [comment]
Hey @dem0nsl4yer thats great I would assign you the issue and let me know if you need anything from me. Thanks.
